[project]
name = "ev-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ev2gym>=2.0.0",
    "multicopula>=0.0.2",
    "numba>=0.63.1",
    "pandapower>=3.3.2",
    "psutil>=7.2.1",
    "setuptools>=80.9.0",
]
